// The living paper skeleton and X-ray files as the mod reads them (neuroflow:phase-paper → Living paper
// skeleton, X-ray files). Pure functions over file text: the prose writes these files, the mod only
// counts, lists and records the person's accept/reject decisions.

/** paper-ledger.md: the latest row per key wins (rows are append-only). */
export const parseLedger = (text: string): { keys: number; final: number } => {
  const latest = new Map<string, string>()
  for (const line of text.split(/\r?\n/)) {
    const cells = line.split('|').map(cell => cell.trim())
    if (cells.length < 7) continue
    const key = cells[1].replace(/`/g, '')
    if (key === '' || /^key$/i.test(key) || /^-+$/.test(key)) continue
    latest.set(key, cells[5].toLowerCase())
  }
  return { keys: latest.size, final: [...latest.values()].filter(status => status === 'final').length }
}

/** gaps.md: `| Gap | Checklist item | Fill with |` rows. */
export const parseGaps = (text: string): { gap: string; item: string; fill: string }[] => {
  const out: { gap: string; item: string; fill: string }[] = []
  for (const line of text.split(/\r?\n/)) {
    const cells = line.split('|').map(cell => cell.trim())
    if (cells.length < 5 || cells[1] === '' || /^gap$/i.test(cells[1]) || /^-+$/.test(cells[1])) continue
    out.push({ gap: cells[1], item: cells[2], fill: cells[3] })
  }
  return out
}

/** The sync date from skeleton.md's generated first line. */
export const skeletonDate = (text: string): string | null => /generated by \/paper --auto sync (\d{4}-\d{2}-\d{2})/.exec(text)?.[1] ?? null

/** Results slots in skeleton.md that still say they have no final result (e.g. `H2`). */
export const openSlots = (text: string): string[] => {
  const out: string[] = []
  for (const line of text.split(/\r?\n/)) {
    const match = /\b(H\d+[a-z]?)\b.*no final result/i.exec(line)
    if (match !== null && !out.includes(match[1])) out.push(match[1])
  }
  return out
}

/** The `/paper --auto status` line (commands/paper.md → Mode: --auto). */
export const autoStatusLine = (on: boolean, ledger: { keys: number; final: number } | null, synced: string | null, gaps: number | null, slots: readonly string[]): string =>
  [
    `Auto paper: ${on ? 'on' : 'off'}`,
    ledger === null ? 'no ledger yet' : `${ledger.keys} facts (${ledger.final} final)`,
    synced === null ? 'never synced' : `synced ${synced}`,
    gaps === null ? null : `${gaps} gap${gaps === 1 ? '' : 's'}`,
    ...slots.slice(0, 3).map(slot => `${slot}: no final result`),
  ]
    .filter(Boolean)
    .join(' | ')

export type XrayFinding = {
  id: string
  scope: string
  sentence?: string
  line?: number
  severity: 'red' | 'orange' | string
  area?: number
  basis?: string
  finding: string
  fix?: string
  status: 'open' | 'accepted' | 'rejected' | string
  reason?: string
}

/** An X-ray .jsonl file; lines that do not parse are skipped. */
export const parseXray = (text: string): XrayFinding[] => {
  const out: XrayFinding[] = []
  for (const line of text.split(/\r?\n/)) {
    if (line.trim() === '') continue
    try {
      const item = JSON.parse(line) as XrayFinding
      if (typeof item.id === 'string' && typeof item.finding === 'string') out.push({ ...item, status: item.status ?? 'open' })
    } catch {
      // a broken line stays in the file and is not shown
    }
  }
  return out
}

/** The newest X-ray of a manuscript: `xray-{stem}-YYYY-MM-DD.jsonl`, latest date first. */
export const newestXray = (names: readonly string[]): string | null =>
  names
    .filter(name => /^xray-.+-\d{4}-\d{2}-\d{2}\.jsonl$/.test(name) && !name.startsWith('xray-changes-'))
    .sort((a, b) => (a.slice(-16) === b.slice(-16) ? a.localeCompare(b) : b.slice(-16).localeCompare(a.slice(-16))))[0] ?? null

/** Records a decision in the .jsonl text: the finding's status (and the reason for a rejection). */
export const decideInJsonl = (text: string, id: string, status: 'accepted' | 'rejected', reason?: string): string =>
  text
    .split(/\r?\n/)
    .map(line => {
      if (line.trim() === '') return line
      try {
        const item = JSON.parse(line) as XrayFinding
        if (item.id !== id) return line
        const next: XrayFinding = { ...item, status }
        if (status === 'rejected' && reason) next.reason = reason
        else delete next.reason
        return JSON.stringify(next)
      } catch {
        return line
      }
    })
    .join('\n')

const escapeRe = (text: string): string => text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')

/** Records a decision in the annotated .md copy: accepted ticks the box; rejected adds the reason. */
export const decideInMarkdown = (text: string, id: string, status: 'accepted' | 'rejected', reason?: string): string => {
  const box = new RegExp(`^(\\s*- )\\[[ x]\\]( ${escapeRe(id)}\\b)(.*?)( — rejected: .*)?$`, 'm')
  return text.replace(box, (_all, lead: string, tag: string, rest: string) =>
    status === 'accepted' ? `${lead}[x]${tag}${rest}` : `${lead}[ ]${tag}${rest} — rejected: ${reason ?? 'no reason given'}`,
  )
}
