import { describe, expect, mock, test } from 'claude-code/testing'

import {
  autoStatusLine,
  decideInJsonl,
  decideInMarkdown,
  newestXray,
  openSlots,
  parseGaps,
  parseLedger,
  parseXray,
  skeletonDate,
} from '../lib/paper'
import { findingLabel, xrayCounts } from '../features/user'
import { fakeFs } from './fakefs'

const ledger = [
  '| Key | Value | Source | Date | Status |',
  '|---|---|---|---|---|',
  '| `participants.n_final` | 23 | `data/data-inventory.md#participants` | 2026-09-28 | draft |',
  '| `participants.n_final` | 24 (12 female) | `data/data-inventory.md#participants` | 2026-09-30 | draft |',
  '| `result.H1` | t(23) = 2.45, p = .022 | `data-analyze/analysis-summary.md#h1` | 2026-10-02 | final |',
].join('\n')

const skeleton = [
  '<!-- generated by /paper --auto sync 2026-10-05 from paper-ledger.md: edit the sources, not this file -->',
  '## Results',
  '- **H1** P300 larger in noise: t(23) = 2.45, p = .022 [src: data-analyze/analysis-summary.md#h1]',
  '- **H2** no final result yet',
].join('\n')

const xrayLines = [
  { id: 'S3.2-1', scope: 'sentence', sentence: 'S3.2', line: 42, severity: 'red', area: 4, basis: 'script:statcheck', finding: 'reported p does not match t and df', fix: 'NEEDS-SOURCE: the p-value', status: 'open' },
  { id: 'S3-1', scope: 'section', severity: 'orange', area: 4, basis: 'model', finding: 'no correction for multiple comparisons is stated', status: 'open' },
].map(item => JSON.stringify(item)).join('\n')

const xrayMd = [
  '# X-ray: results.md (2026-10-07)',
  'S3.2 (l. 42) This effect was significant, t(23) = 2.45, p = .002.',
  '  - [ ] S3.2-1 red · Area 4 · statcheck: reported p does not match t and df.',
  'Section findings:',
  '  - [ ] S3-1 orange · Area 4 · six ERP comparisons; no correction is stated.',
].join('\n')

describe('living paper files', () => {
  test('the ledger counts the latest row per key; the skeleton gives its date and open slots', () => {
    expect(parseLedger(ledger)).toEqual({ keys: 2, final: 1 })
    expect(skeletonDate(skeleton)).toBe('2026-10-05')
    expect(openSlots(skeleton)).toEqual(['H2'])
    expect(parseGaps('| Gap | Checklist item | Fill with |\n|---|---|---|\n| reference electrode | COBIDAS-MEEG 3.2 | /data-preprocess |\n')).toEqual([
      { gap: 'reference electrode', item: 'COBIDAS-MEEG 3.2', fill: '/data-preprocess' },
    ])
  })

  test('the status line reads as commands/paper.md shows it', () => {
    expect(autoStatusLine(true, { keys: 42, final: 7 }, '2026-10-07', 5, ['H2'])).toBe('Auto paper: on | 42 facts (7 final) | synced 2026-10-07 | 5 gaps | H2: no final result')
    expect(autoStatusLine(false, null, null, null, [])).toBe('Auto paper: off | no ledger yet | never synced')
  })
})

describe('x-ray files', () => {
  test('findings parse; the newest X-ray is found by its date, not the change log', () => {
    const findings = parseXray(`${xrayLines}\nnot json\n`)
    expect(findings.map(item => item.id)).toEqual(['S3.2-1', 'S3-1'])
    expect(xrayCounts(findings)).toEqual({ red: 1, orange: 1, open: 2, decided: 0 })
    expect(findingLabel(findings[0])).toBe('● S3.2-1 red · Area 4 · reported p does not match t and df')
    expect(newestXray(['xray-results-2026-10-01.jsonl', 'xray-results-2026-10-07.jsonl', 'xray-changes-2026-10-08.md', 'xray-results-2026-10-07.md'])).toBe('xray-results-2026-10-07.jsonl')
  })

  test('decisions land in both files: accepted ticks the box, rejected keeps the reason', () => {
    const accepted = parseXray(decideInJsonl(xrayLines, 'S3.2-1', 'accepted'))
    expect(accepted[0].status).toBe('accepted')
    expect(accepted[1].status).toBe('open')
    const rejected = parseXray(decideInJsonl(xrayLines, 'S3-1', 'rejected', 'corrected in the supplement'))
    expect(rejected[1]).toMatchObject({ status: 'rejected', reason: 'corrected in the supplement' })
    expect(decideInMarkdown(xrayMd, 'S3.2-1', 'accepted')).toContain('  - [x] S3.2-1 red')
    const md = decideInMarkdown(xrayMd, 'S3-1', 'rejected', 'corrected in the supplement')
    expect(md).toContain('  - [ ] S3-1 orange · Area 4 · six ERP comparisons; no correction is stated. — rejected: corrected in the supplement')
    expect(md).toContain('  - [ ] S3.2-1 red')
  })
})

describe('paper commands in a session', () => {
  const root = '/work/proj'
  const files = {
    [`${root}/.neuroflow/project_config.md`]: '---\nnf_schema: 1\nactive_phase: paper\npaper_auto: on\n---\n',
    [`${root}/.neuroflow/paper/paper-ledger.md`]: ledger,
    [`${root}/.neuroflow/paper/skeleton.md`]: skeleton,
    [`${root}/.neuroflow/paper/gaps.md`]: '| Gap | Checklist item | Fill with |\n|---|---|---|\n| reference electrode | COBIDAS-MEEG 3.2 | /data-preprocess |\n',
    [`${root}/.neuroflow/paper/xray-results-2026-10-07.jsonl`]: xrayLines,
    [`${root}/.neuroflow/paper/xray-results-2026-10-07.md`]: xrayMd,
  }

  test('--auto status is answered in code; --xray view opens the findings and a key press accepts one', { options: { runtime: 'observe' } }, async ($, on) => {
    const fs = fakeFs(on, files, root)
    mock.env(on, { HOME: '/home/me' })
    mock.clock(on, { now: 0 })
    on('session.start', ($, e) => ({ cwd: e.cwd }))
    on('ui.status', () => ({ value: undefined }))
    on('ui.open', () => ({ value: undefined }))
    let ranProse = false
    on('command.run', () => {
      ranProse = true
      return { text: 'prose', ref: 1 }
    })
    await $.session.start({ cwd: root, surface: 'terminal', isInteractive: true })
    const status = await $.command.run({ command: 'neuroflow:paper', args: '--auto status' })
    expect(status.text).toContain('Auto paper: on | 2 facts (1 final) | synced 2026-10-05 | 1 gap | H2: no final result')
    const opened = await $.command.run({ command: 'neuroflow:paper', args: '--xray view' })
    expect(opened.text).toBe('X-ray results-2026-10-07: 1 red, 1 orange open; 0 decided.')
    expect(ranProse).toBe(false)
    const pane = await $.ui.mount({
      plugin: 'neuroflow', surface: 'terminal', component: 'Pane', requestId: 'nf-xray',
      props: { title: 'X-ray', isFocused: true, bodyColumns: 100, placement: 'inline', scroll: { offset: 0, bodyRows: 20 }, view: {} },
    } as never)
    expect(JSON.stringify(await pane.drawn())).toContain('S3.2-1')
    await pane.press({ key: 'nf-xray-accept' })
    expect(fs.files[`${root}/.neuroflow/paper/xray-results-2026-10-07.md`]).toContain('  - [x] S3.2-1 red')
    expect(parseXray(fs.files[`${root}/.neuroflow/paper/xray-results-2026-10-07.jsonl`])[0].status).toBe('accepted')
    await $.command.run({ command: 'neuroflow:paper', args: '--xray manuscript/results.md' })
    expect(ranProse).toBe(true)
  })
})
